site_name: SHModbus Documentation
site_description: Documentation for SHModbus - A Modbus TCP/IP client application
site_author: IotSkyHub
site_url: https://iotskyhub.github.io/shmodbus-docs/

repo_name: iotskyhub/shmodbus-docs
repo_url: https://github.com/iotskyhub/shmodbus-docs

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - navigation.instant

nav:
  - Home: index.md
  - Getting Started: en/getting-started.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/iotskyhub

extra_css:
  - stylesheets/extra.css